server:
  port: 8090
  tomcat: 
    max-swallow-size: -1
  servlet:
    context-path:
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
        
management:
 endpoints:
  web:
   exposure:
    include: metrics,httptrace
    
spring:
  servlet:
     multipart: 
        max-file-size: 10MB
        max-request-size: 10MB
  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  aop:
    proxy-target-class: true
  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://192.168.1.186:3306/shunchao?characterEncoding=UTF-8&useUnicode=true&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/shunchao/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 4
      # 默认数据库表下划线命名
      table-underline: true
#Mybatis输出sql日志
logging:
  level:
    org.jeecg.modules.system.mapper : debug
jeecg :
  path :
    #文件上传根目录 设置
    upload: D://upFiles//
    cases:
      basecpc: cases
      inventions: inventions
      utility_models: utility_models
      designs: designs
      pCT_inventions: PCT_inventions
      pCT_utility: PCT_utility
      reexamination: Reexamination
      invalidation: Invalidation
      notices: notices
connecturl: 121.36.230.204:8080/jeecg-boot
#connecturl: localhost:8080/jeecg-boot
#connecturl: 192.168.1.177/jeecg-boot

#商标网址信息
trademark:
  URL: http://wssq.sbj.cnipa.gov.cn:9080/tmsve/
  PINWORD: 456123
access_data:
  char_set: gb2312
  user:
  password: 
